<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_5f1b413915e9e',
			'title'                 => 'Contact information',
			'fields'                => array(
				array(
					'key'               => 'field_5f1b4bc17c4ce',
					'label'             => 'Name',
					'name'              => 'contact_name',
					'type'              => 'text',
					'instructions'      => 'Name of person or department responsible for the site\'s content.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => get_bloginfo( 'name' ),
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5f1b4147215f7',
					'label'             => 'Email',
					'name'              => 'contact_email',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5f1b50cd74b44',
							'label'             => 'Email address',
							'name'              => 'contact_email_address',
							'type'              => 'text',
							'instructions'      => 'Email address you wish to appear in the footer.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b50ef74b45',
							'label'             => 'Enable custom text?',
							'name'              => 'contact_email_text_enable',
							'type'              => 'checkbox',
							'instructions'      => 'Enable custom email text instead of the address.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'true' => 'Yes',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'horizontal',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_5f1b518971f0a',
							'label'             => 'Custom email text',
							'name'              => 'contact_email_text',
							'type'              => 'text',
							'instructions'      => 'Provide clear text to the user so they will understand they are clicking an email address.',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5f1b50ef74b45',
										'operator' => '==',
										'value'    => 'true',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5f1b53d5c213f',
					'label'             => 'Address',
					'name'              => 'contact_address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5f1b53f633068',
							'label'             => 'Street',
							'name'              => 'address_street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b541033069',
							'label'             => 'City',
							'name'              => 'address_locality',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b541c3306a',
							'label'             => 'State or Region',
							'name'              => 'address_region',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b54413306b',
							'label'             => 'Zip code',
							'name'              => 'address_postal_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5f1b551f483f7',
					'label'             => 'Phone',
					'name'              => 'contact_telephone',
					'type'              => 'text',
					'instructions'      => 'Provide the primary phone number for contacting the owner\'s of the site.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5f1b55be0f861',
					'label'             => 'Fax number',
					'name'              => 'contact_fax',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5f1b53d5c2321',
					'label'             => 'Social Media',
					'name'              => 'contact_social_media',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5f1b53f633022',
							'label'             => 'Facebook',
							'name'              => 'facebook',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b541033068',
							'label'             => 'Instagram',
							'name'              => 'instagram',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b541c33032',
							'label'             => 'Twitter',
							'name'              => 'twitter',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b544133033',
							'label'             => 'Linkedin',
							'name'              => 'linkedin',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f1b544133035',
							'label'             => 'YouTube',
							'name'              => 'youtube',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-footer',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => 'Contact information placed in the footer of the site.',
			'show_in_rest'          => 1,
		)
	);
endif;
