<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e99c76101ede',
			'title'                 => 'Settings',
			'fields'                => array(
				array(
					'key'               => 'field_5e99c79b58ae3',
					'label'             => 'Site Hostname',
					'name'              => 'hostname',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e99c7b058ae4',
					'label'             => 'Site Shortname',
					'name'              => 'short_name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e99c7ef60fb0',
					'label'             => 'Google Analytics Code',
					'name'              => 'google_analytics',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e99c80860fb1',
					'label'             => 'Google Tag Manager',
					'name'              => 'google_tag_manager',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ebed84c690bf',
					'label'             => 'Enable Social Media Sharing Buttons',
					'name'              => 'enable_social_media_sharing_buttons',
					'type'              => 'true_false',
					'instructions'      => 'Enabling this option will add sharing buttons for Facebook, LinkedIn, and Twitter.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => 'Enables Social Media Sharing Buttons on Posts',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60bf53da46a32',
					'label'             => 'Enable Bootstrap CSS',
					'name'              => 'bs_css',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60bf540046a33',
					'label'             => 'Enable Bootstrap JS',
					'name'              => 'bs_js',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'discussion',
				1 => 'comments',
				2 => 'slug',
				3 => 'author',
				4 => 'format',
				5 => 'page_attributes',
				6 => 'send-trackbacks',
			),
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5f6e19adc1904',
			'title'                 => 'Settings (Calendar)',
			'fields'                => array(
				array(
					'key'               => 'field_5f6e1beb55f49',
					'label'             => 'Notes',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => 'This will allow you to include events from the <a href="https://calendar.missouri.edu/" target="_blank">Mizzou Calendar</a>. Events from the Mizzou Calendar will not appear in the WordPress Dashboard. These events must be added up and updated through the Mizzou Calendar.',
					'new_lines'         => 'wpautop',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_5f6e19df2a63e',
					'label'             => 'Calendar Exception Email Address',
					'name'              => 'calendar_exception_email',
					'type'              => 'email',
					'instructions'      => 'Should be the person that should receive the notice that a calendar issue has occurred. Usually, it\'s the site Admin',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_5f6e1a0b2a63f',
					'label'             => 'How to Filter Calendar Results',
					'name'              => 'method',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'search'     => 'Search',
						'department' => 'Department',
						'type'       => 'Type',
						'keyword'    => 'Keyword',
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5f6e1a7f2a640',
					'label'             => 'Term',
					'name'              => 'term',
					'type'              => 'text',
					'instructions'      => '<p>If you selected <strong>Department</strong> previously then this field will have the group_id. If you selected <strong>Type</strong> earlier then this field will have the Event Type.</p>
	<p>If you selected either <strong>Type</strong> or <strong>Keyword</strong> then this field can accept multiple values separated by a single space.</p>',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5f577c3779b9d',
			'title'                 => 'Settings - Footer (Contact Information)',
			'fields'                => array(
				array(
					'key'               => 'field_5f577cda48057',
					'label'             => 'Name',
					'name'              => 'contact_name',
					'type'              => 'text',
					'instructions'      => 'Name of person or department responsible for the site\'s content.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5f577d1748058',
					'label'             => 'Email',
					'name'              => 'contact_email',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5f577d3948059',
							'label'             => 'Email address',
							'name'              => 'contact_email_address',
							'type'              => 'email',
							'instructions'      => 'Email address you wish to appear in the footer.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_5f577d644805a',
							'label'             => 'Enable custom text?',
							'name'              => 'contact_email_text_enable',
							'type'              => 'checkbox',
							'instructions'      => 'Enable custom email text instead of the address.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'true' => 'Yes',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'horizontal',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_5f577dc44805b',
							'label'             => 'Custom email text',
							'name'              => 'contact_email_text',
							'type'              => 'text',
							'instructions'      => 'Provide clear text to the user so they will understand they are clicking an email address.',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5f577d644805a',
										'operator' => '==',
										'value'    => 'true',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5f577c3c48052',
					'label'             => 'Address',
					'name'              => 'contact_address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5f577c5348053',
							'label'             => 'Street',
							'name'              => 'street_address',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f577c6c48054',
							'label'             => 'City',
							'name'              => 'address_locality',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f577c8648055',
							'label'             => 'State or Region',
							'name'              => 'state_region',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5f577c9e48056',
							'label'             => 'Zip code',
							'name'              => 'address_postal_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5f577e464805c',
					'label'             => 'Phone',
					'name'              => 'contact_telephone',
					'type'              => 'text',
					'instructions'      => 'Provide the primary phone number for contacting the owner\'s of the site.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5f577e6f4805d',
					'label'             => 'Fax number',
					'name'              => 'contact_fax',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_606b50c3a713d',
					'label'             => 'Social Media',
					'name'              => 'social_media',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Add Social Icon',
					'sub_fields'        => array(
						array(
							'key'               => 'field_606b50d5a713e',
							'label'             => 'Name',
							'name'              => 'name',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_606b50dda713f',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-footer',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => 'Contact information placed in the footer of the site.',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e99ce5f15650',
			'title'                 => 'Settings - Footer (Footer Options)',
			'fields'                => array(
				array(
					'key'               => 'field_5f577f91dc913',
					'label'             => 'Theme',
					'name'              => 'footer_theme',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'dark'  => 'Dark Theme',
						'light' => 'Light Theme',
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'dark',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'field_5f57801bdc914',
					'label'             => 'Name',
					'name'              => 'footer_contact_card_title',
					'type'              => 'text',
					'instructions'      => 'Header for Contact Card',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Contact Us',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_606c44f7b2d63',
					'label'             => 'Schema',
					'name'              => 'footer_schema',
					'type'              => 'radio',
					'instructions'      => 'Enable schema information for SEO optimization on footer contacts?',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'yes' => 'Yes',
						'no'  => 'No',
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'no',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-footer',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e99cb32ec364',
			'title'                 => 'Settings (Colors)',
			'fields'                => array(
				array(
					'key'               => 'field_606b512dce844',
					'label'             => 'Social Icon Color',
					'name'              => 'social_icon_color',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'gold'  => 'Gold',
						'black' => 'Black',
						'white' => 'White',
					),
					'default_value'     => 'gold',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5e99cb3dd06b6',
					'label'             => 'Apple Mask Color',
					'name'              => 'apple_mask_color',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '#000000',
				),
				array(
					'key'               => 'field_5e99cbe1d06b7',
					'label'             => 'Microsoft Tile Color',
					'name'              => 'microsoft_icon_color',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '#f1b82d',
				),
				array(
					'key'               => 'field_5e99cc15d06b8',
					'label'             => 'Site Icon Color',
					'name'              => 'site_icon_color',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'gold'       => 'Gold',
						'black'      => 'Black',
						'dark-grey'  => 'Dark Grey',
						'light-grey' => 'Light Grey',
						'tan'        => 'Tan',
						'white'      => 'White',
					),
					'default_value'     => 'gold',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5e99cc94d06b9',
					'label'             => 'Primary Navigation Color',
					'name'              => 'primary_nav_color',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'gold'  => 'Gold',
						'black' => 'Black',
						'grey'  => 'Grey',
						'tan'   => 'Tan',
						'white' => 'White',
					),
					'default_value'     => 'gold',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5e99ccd8d06ba',
					'label'             => 'Sub Navigation Color',
					'name'              => 'sub_nav_color',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'gold'  => 'Gold',
						'black' => 'Black',
						'grey'  => 'Grey',
						'tan'   => 'Tan',
						'white' => 'White',
					),
					'default_value'     => 'gold',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_606c47ba218e6',
			'title'                 => 'Settings (Custom Post Types)',
			'fields'                => array(
				array(
					'key'               => 'field_5e99d1251fffa',
					'label'             => 'Disable Staff',
					'name'              => 'disable_staff',
					'type'              => 'true_false',
					'instructions'      => 'Disables the Staff custom post type',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e99cfc19ff86',
			'title'                 => 'Settings (Header)',
			'fields'                => array(
				array(
					'key'               => 'field_5e99c8c460fb4',
					'label'             => 'Subhead Name',
					'name'              => 'subhead_name',
					'type'              => 'text',
					'instructions'      => 'Appears under the site name',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e99c8d060fb5',
					'label'             => 'Subhead URL',
					'name'              => 'subhead_url',
					'type'              => 'url',
					'instructions'      => 'Turns subhead name into a link',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_606c471cde136',
			'title'                 => 'Settings (Search)',
			'fields'                => array(
				array(
					'key'               => 'field_5e99d0212b5f0',
					'label'             => 'Google Search Console ID',
					'name'              => 'google_search_console',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e99d0162b5ef',
					'label'             => 'Google CSE ID',
					'name'              => 'google_cse_id',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	endif;

