<?php
add_action(
	'acf/include_fields',
	function() {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6422fdbc26190',
				'title'                 => 'MizzouDS-big-message',
				'fields'                => array(
					array(
						'key'               => 'field_6422fdbcbe796',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6422fdccbe797',
						'label'             => 'Message',
						'name'              => 'message',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
						'delay'             => 0,
					),
					array(
						'key'               => 'field_6422fddfbe798',
						'label'             => 'Buttons',
						'name'              => 'buttons',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 3,
						'collapsed'         => '',
						'button_label'      => 'Add Button',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6422fdefbe799',
								'label'             => 'Button',
								'name'              => 'button',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'parent_repeater'   => 'field_6422fddfbe798',
							),
						),
					),
					array(
						'key'               => 'field_64232c7fd1cad',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_64248cf26bd04',
								'label'             => 'Layer Background Clone',
								'name'              => 'layer_background_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64248336fd14b',
									1 => 'field_6424837bfd14c',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_645ba155b0c44',
								'label'             => 'Button Style',
								'name'              => 'button_style',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'primary'   => 'Primary Branded',
									'secondary' => 'Secondary Branded',
								),
								'default_value'     => 'primary',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_645ba1d67b16b',
								'label'             => 'Corner Decoration',
								'name'              => 'include_corner_decoration',
								'aria-label'        => '',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'message'           => 'Include Gold Decoration in Top Left Corner',
								'default_value'     => 0,
								'ui'                => 0,
								'ui_on_text'        => '',
								'ui_off_text'       => '',
							),
							array(
								'key'               => 'field_6423300c17512',
								'label'             => 'Plus Decoration Clone',
								'name'              => 'plus_decoration_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64232d4fb3cc0',
									1 => 'field_64232d75b3cc1',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'post',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6422fe12ad9e1',
				'title'                 => 'MizzouDS-by-the-numbers',
				'fields'                => array(
					array(
						'key'               => 'field_6422fe125aab4',
						'label'             => 'Kicker',
						'name'              => 'kicker',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6422fe4b5aab5',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6422fe5b5aab6',
						'label'             => 'Numbers',
						'name'              => 'numbers',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 2,
						'max'               => 3,
						'collapsed'         => '',
						'button_label'      => 'Add Number Card',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6422fe835aab7',
								'label'             => 'Number',
								'name'              => 'number',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6422fe5b5aab6',
							),
							array(
								'key'               => 'field_6422fe8f5aab8',
								'label'             => 'Message',
								'name'              => 'message',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6422fe5b5aab6',
							),
						),
					),
					array(
						'key'               => 'field_642490d91875a',
						'label'             => 'Button',
						'name'              => 'button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6422feb4e3b08',
				'title'                 => 'MizzouDS-call-to-action',
				'fields'                => array(
					array(
						'key'               => 'field_6422feb567019',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6422fecc6701a',
						'label'             => 'Content',
						'name'              => 'content',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 0,
					),
					array(
						'key'               => 'field_6422fef06701b',
						'label'             => 'Buttons',
						'name'              => 'buttons',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 3,
						'collapsed'         => '',
						'button_label'      => 'Add Button',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6422fef96701c',
								'label'             => 'Button',
								'name'              => 'button',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'parent_repeater'   => 'field_6422fef06701b',
							),
						),
					),
					array(
						'key'               => 'field_6422ff146701d',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_64248d37bdb08',
								'label'             => 'Layer Background Clone',
								'name'              => 'layer_background_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64248336fd14b',
									1 => 'field_6424837bfd14c',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_64248d68bdb09',
								'label'             => 'Content Background Clone',
								'name'              => 'content_background_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_642483c7fd14d',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_64232a33f522f',
								'label'             => 'Button Style',
								'name'              => 'button_style',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'brand-primary' => 'Branded Primary',
									'gold-ghost'    => 'Gold Ghost',
									'outline'       => 'Outline',
								),
								'default_value'     => '',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_642330352ff08',
								'label'             => 'Plus Decoration Clone',
								'name'              => 'plus_decoration_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64232d4fb3cc0',
									1 => 'field_64232d75b3cc1',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6447ce2b83fd3',
				'title'                 => 'MizzouDS-card-deck',
				'fields'                => array(
					array(
						'key'               => 'field_6447ce2b9edcf',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6447ce3e9edd0',
						'label'             => 'Content',
						'name'              => 'content',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'rows'              => '',
						'placeholder'       => '',
						'new_lines'         => '',
					),
					array(
						'key'               => 'field_6447ce549edd1',
						'label'             => 'Card Deck',
						'name'              => 'cards',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => 'field_6447cef49edd7',
						'button_label'      => 'Add Card',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6447ce649edd2',
								'label'             => 'Media Type',
								'name'              => 'mediaType',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'image' => 'Image',
									'video' => 'Video',
								),
								'default_value'     => 'image',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
								'parent_repeater'   => 'field_6447ce549edd1',
							),
							array(
								'key'               => 'field_6447ce899edd3',
								'label'             => 'Image',
								'name'              => 'image',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6447ce649edd2',
											'operator' => '==',
											'value'    => 'image',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_6447ce549edd1',
							),
							array(
								'key'               => 'field_6447ceab9edd4',
								'label'             => 'Video',
								'name'              => 'video',
								'aria-label'        => '',
								'type'              => 'group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6447ce649edd2',
											'operator' => '==',
											'value'    => 'video',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'layout'            => 'block',
								'parent_repeater'   => 'field_6447ce549edd1',
								'sub_fields'        => array(
									array(
										'key'           => 'field_6447cebe9edd5',
										'label'         => 'Video Title',
										'name'          => 'title',
										'aria-label'    => '',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'maxlength'     => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
									),
									array(
										'key'           => 'field_6447cec89edd6',
										'label'         => 'Video ID',
										'name'          => 'id',
										'aria-label'    => '',
										'type'          => 'text',
										'instructions'  => 'Found in the URL of the video after <code>https://youtube.com/watch?v=</code>',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'maxlength'     => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
									),
								),
							),
							array(
								'key'               => 'field_6447cef49edd7',
								'label'             => 'Title',
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6447ce549edd1',
							),
							array(
								'key'               => 'field_6447cefb9edd8',
								'label'             => 'Content',
								'name'              => 'content',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6447ce549edd1',
							),
							array(
								'key'               => 'field_6447cf0a9edd9',
								'label'             => 'Links',
								'name'              => 'links',
								'aria-label'        => '',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'layout'            => 'table',
								'pagination'        => 0,
								'min'               => 0,
								'max'               => 0,
								'collapsed'         => 'field_6447cf1b9edda',
								'button_label'      => 'Add Link',
								'rows_per_page'     => 20,
								'parent_repeater'   => 'field_6447ce549edd1',
								'sub_fields'        => array(
									array(
										'key'             => 'field_6447cf1b9edda',
										'label'           => 'Link',
										'name'            => 'link',
										'aria-label'      => '',
										'type'            => 'link',
										'instructions'    => '',
										'required'        => 0,
										'conditional_logic' => 0,
										'wrapper'         => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'return_format'   => 'array',
										'parent_repeater' => 'field_6447cf0a9edd9',
									),
								),
							),
						),
					),
					array(
						'key'               => 'field_6447cf609eddb',
						'label'             => 'Button',
						'name'              => 'button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_6447cf6a9eddc',
						'label'             => 'displayOptions Clone',
						'name'              => 'displayoptions_clone',
						'aria-label'        => '',
						'type'              => 'clone',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'clone'             => array(
							0 => 'group_64232d4f917a1',
						),
						'display'           => 'seamless',
						'layout'            => 'block',
						'prefix_label'      => 0,
						'prefix_name'       => 0,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'post',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6422ffabdf21c',
				'title'                 => 'MizzouDS-events',
				'fields'                => array(
					array(
						'key'               => 'field_6422ffac12241',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6422ffbf12242',
						'label'             => 'Events Options',
						'name'              => 'eventsOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6422ffe412243',
								'label'             => 'Number of Events',
								'name'              => 'number_of_events',
								'aria-label'        => '',
								'type'              => 'range',
								'instructions'      => 'Choose the number of events you wish to have appear',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => 3,
								'min'               => 1,
								'max'               => 4,
								'step'              => 1,
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_6423001412244',
								'label'             => 'How to Filter Calendar Results',
								'name'              => 'method',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'search'     => 'Search',
									'department' => 'Department',
									'type'       => 'Type',
									'keyword'    => 'Keyword',
								),
								'default_value'     => 'search',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_6423007612245',
								'label'             => 'Term',
								'name'              => 'term',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '<p>If you selected <strong>Department</strong> previously then this field will have the group_id. If you selected <strong>Type</strong> earlier then this field will have the Event Type.</p>
		<p>If you selected either <strong>Type</strong> or <strong>Keyword</strong> then this field can accept multiple values separated by a single space.</p>',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
						),
					),
					array(
						'key'               => 'field_6423009912246',
						'label'             => 'More Events Link',
						'name'              => 'button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_64233062c6c88',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6423306cc6c89',
								'label'             => 'Plus Decoration Clone',
								'name'              => 'plus_decoration_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64232d4fb3cc0',
									1 => 'field_64232d75b3cc1',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_642300bdc27f5',
				'title'                 => 'MizzouDS-featured-news',
				'fields'                => array(
					array(
						'key'               => 'field_642300bd06a7b',
						'label'             => 'Header Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642300fb06a7c',
						'label'             => 'News Cards',
						'name'              => 'cards',
						'aria-label'        => '',
						'type'              => 'relationship',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'post_type'         => '',
						'taxonomy'          => '',
						'filters'           => array(
							0 => 'search',
							1 => 'post_type',
							2 => 'taxonomy',
						),
						'return_format'     => 'object',
						'min'               => '',
						'max'               => 4,
						'elements'          => array(
							0 => 'featured_image',
						),
					),
					array(
						'key'               => 'field_6423013606a7d',
						'label'             => 'Read More Button',
						'name'              => 'button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6423014a9fc5a',
				'title'                 => 'MizzouDS-hero',
				'fields'                => array(
					array(
						'key'               => 'field_6423018bca741',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_64230199ca742',
						'label'             => 'Overline',
						'name'              => 'overline',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642301e2ca744',
						'label'             => 'Buttons',
						'name'              => 'buttons',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 2,
						'collapsed'         => '',
						'button_label'      => 'Add Button',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_642301edca745',
								'label'             => 'Button',
								'name'              => 'button',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'parent_repeater'   => 'field_642301e2ca744',
							),
						),
					),
					array(
						'key'               => 'field_6423014aca73f',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_64230173ca740',
								'label'             => 'Background Image',
								'name'              => 'image',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_642301b1ca743',
								'label'             => 'Content Alignment',
								'name'              => 'alignment',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'center' => 'Center',
									'left'   => 'Left',
									'right'  => 'Right',
								),
								'default_value'     => 'center',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_64230234c7cb1',
				'title'                 => 'MizzouDS-link-list',
				'fields'                => array(
					array(
						'key'               => 'field_642302346c6cd',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642302406c6ce',
						'label'             => 'Links',
						'name'              => 'links',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 3,
						'max'               => 9,
						'collapsed'         => '',
						'button_label'      => 'Add Link',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6423024d6c6cf',
								'label'             => 'link',
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'parent_repeater'   => 'field_642302406c6ce',
							),
						),
					),
					array(
						'key'               => 'field_64233099df7a2',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_642330a2df7a3',
								'label'             => 'Plus Decoration Clone',
								'name'              => 'plus_decoration_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64232d4fb3cc0',
									1 => 'field_64232d75b3cc1',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6423027fb6d65',
				'title'                 => 'MizzouDS-quote',
				'fields'                => array(
					array(
						'key'               => 'field_6423027f91b73',
						'label'             => 'Header Kicker',
						'name'              => 'kicker',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6423029991b74',
						'label'             => 'Header Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642302bc91b75',
						'label'             => 'Quote',
						'name'              => 'quote',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_642302c491b76',
								'label'             => 'Quote Attribution',
								'name'              => 'attribution',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_642302d991b77',
								'label'             => 'Degree',
								'name'              => 'degree',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_642302e691b78',
								'label'             => 'Quote Text',
								'name'              => 'content',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'rows'              => '',
								'placeholder'       => '',
								'new_lines'         => '',
							),
							array(
								'key'               => 'field_642302fa91b79',
								'label'             => 'Quote Image',
								'name'              => 'image',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
							),
						),
					),
					array(
						'key'               => 'field_6423031691b7a',
						'label'             => 'Button',
						'name'              => 'button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_642330d54313a',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_642330e94313b',
								'label'             => 'Layer Background',
								'name'              => 'layer_background',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'miz-black-100' => 'Black 100',
									'miz-white'     => 'White',
								),
								'default_value'     => 'miz-white',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_64230329f0255',
				'title'                 => 'MizzouDS-split-layout',
				'fields'                => array(
					array(
						'key'               => 'field_642303c2db9d8',
						'label'             => 'Title',
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642303cbdb9d9',
						'label'             => 'Kicker',
						'name'              => 'kicker',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_642303f4db9db',
						'label'             => 'Message',
						'name'              => 'message',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 0,
					),
					array(
						'key'               => 'field_6423040cdb9dc',
						'label'             => 'Buttons',
						'name'              => 'buttons',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 2,
						'collapsed'         => '',
						'button_label'      => 'Add Button',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_64230416db9dd',
								'label'             => 'Button',
								'name'              => 'button',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'parent_repeater'   => 'field_6423040cdb9dc',
							),
						),
					),
					array(
						'key'               => 'field_6447cc1c5d161',
						'label'             => 'Media Type',
						'name'              => 'mediaType',
						'aria-label'        => '',
						'type'              => 'button_group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'image' => 'Image',
							'video' => 'Video',
						),
						'default_value'     => '',
						'return_format'     => 'value',
						'allow_null'        => 0,
						'layout'            => 'horizontal',
					),
					array(
						'key'               => 'field_642303dddb9da',
						'label'             => 'Image',
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_6447cc1c5d161',
									'operator' => '==',
									'value'    => 'image',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'preview_size'      => 'medium',
					),
					array(
						'key'               => 'field_6447cd1eaa704',
						'label'             => 'Video',
						'name'              => 'video',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_6447cc1c5d161',
									'operator' => '==',
									'value'    => 'video',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6447cdb81fb35',
								'label'             => 'Video Title',
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_6447cdc21fb36',
								'label'             => 'Video ID',
								'name'              => 'id',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => 'Found in the URL of the video after <code>https://youtube.com/watch?v=</code>',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
						),
					),
					array(
						'key'               => 'field_6423032adb9d4',
						'label'             => 'Appearance',
						'name'              => 'displayOptions',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6423039bdb9d7',
								'label'             => 'Layout Media Location',
								'name'              => 'media_align',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'left'  => 'Left',
									'right' => 'Right',
								),
								'default_value'     => 'left',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_64230346db9d5',
								'label'             => 'Variant',
								'name'              => 'variant',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'level'  => 'Level',
									'offset' => 'Offset',
								),
								'default_value'     => 'level',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_64248e5e2b9ea',
								'label'             => 'Layer Background Clone',
								'name'              => 'layer_background_clone',
								'aria-label'        => '',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_64248336fd14b',
									1 => 'field_6424837bfd14c',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_642324c747a9c',
								'label'             => 'Content Background',
								'name'              => 'content_background',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_64230346db9d5',
											'operator' => '==',
											'value'    => 'offset',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'light'       => 'Light',
									'dark'        => 'Dark',
									'transparent' => 'Transparent',
								),
								'default_value'     => '',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
							array(
								'key'               => 'field_6423251a47a9d',
								'label'             => 'Overlay',
								'name'              => 'overlay',
								'aria-label'        => '',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_64248336fd14b',
											'operator' => '==',
											'value'    => 'image',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'none' => 'No Overlay',
									70     => '70% #000',
								),
								'default_value'     => '',
								'return_format'     => 'value',
								'allow_null'        => 0,
								'layout'            => 'horizontal',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'acf-field-group',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);
	}
);



